---
- hosts: all
  become: yes
  remote_user: root
  vars:
    # disk id on MacBook
    - local_disk_id: disk3
    # disk partitions to unmout as seen via df -h
    - local_disk_partitions: []
    #Linux distribution to download
    - distro_download_url: http://archlinuxarm.org/os/
    - distro_archive_name: ArchLinuxARM-rpi-2-latest
    - boot_disk: { id: 1, name: boot, fs: vfat }
    - root_disk: { id: 2, name: root, fs: ext4 }
    - disks: 
        - { id: "{{boot_disk.id}}", name: "{{boot_disk.name}}", fs: "{{boot_disk.fs}}" }
        - { id: "{{root_disk.id}}", name: "{{root_disk.name}}", fs: "{{root_disk.fs}}" }
    - device_id: sdb
  pre_tasks:
    - name: Unmount SD Card partitions
      command: diskutil unmountDisk /dev/{{local_disk_id}}
      delegate_to: 127.0.0.1
      with_items: local_disk_partitions
      become: sudo
    - name: Set permissions to SD Card
      command: chmod 0777 /dev/{{local_disk_id}}
      delegate_to: 127.0.0.1
      become: sudo
  tasks:
    - apt: update_cache=yes
    - name: Install packages
      package: name={{item}} state=latest
      with_items:
        - dosfstools
        - bsdtar
        - parted
    - name: Remove previously created partitions
      command: dd if=/dev/zero of=/dev/{{device_id}} bs=512 count=1
    - name: Create partitions
      shell: parted -a optimal /dev/{{device_id}} -- mklabel msdos mkpart primary fat32 1MiB 100MiB mkpart primary ext4 100MiB -1s && parted /dev/{{device_id}} set 1 boot on
    - name: Format partitions
      command: "mkfs.{{item.fs}} /dev/{{device_id}}{{item.id}}"
      with_items: disks
    - name: Mount partitions
      mount: name=/tmp/{{item.name}} src=/dev/{{device_id}}{{item.id}} fstype={{item.fs}} state=mounted
      with_items: disks
    - name: Download distro
      get_url: url={{distro_download_url}}{{distro_archive_name}}.tar.gz dest=/tmp/{{distro_archive_name}}.tar.gz
    - name: Unarchive distro to root disk
      shell: su -c "bsdtar -xpf /tmp/{{distro_archive_name}}.tar.gz -C /tmp/{{root_disk.name}}" && sync
      become_user: root
    - name: Move boot files to the first partition
      command: mv /tmp/{{root_disk.name}}/boot/* /tmp/{{boot_disk.name}} 
    - name: Unmount disks
      mount: name={{item.name}} state=unmounted
      with_items: disks
    - name: Generate image copy
      command: dd if=/dev/{{device_id}} of=/vagrant/{{distro_archive_name}}.img bs=1M
